# Generated by Django 5.2.4 on 2025-07-16 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="path_input",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path_input1", models.CharField(max_length=250)),
                ("path_input2", models.CharField(max_length=250)),
                ("upload_date", models.DateTimeField(verbose_name="date uploaded")),
            ],
        ),
    ]
